apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: promtail
spec:
  interval: 1h
  dependsOn:
    - name: loki
  chart:
    spec:
      chart: promtail
      version: "6.x"
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
  timeout: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    # Wysyłaj logi (w tym kontrolerów Fluxa) do Loki przez gateway.
    config:
      clients:
        - url: http://loki-gateway.monitoring.svc.cluster.local/loki/api/v1/push
