#ENC[AES256_GCM,data:XqIL2tB+IzkXAK2xqtEgvntG0s1mjJlotS1zZWp7rH7ZGg==,iv:wwnLXuKLwIZSIY6laIK6jRBG7JbLyArBBQcLNY+QqKw=,tag:PSIYVbRJf2SPeDiEwpEG7Q==,type:comment]
#ENC[AES256_GCM,data:ucBWgXqT1+3+z8D3gifBYDBx4GuipgQ6YDtZQpgAg0oLFrd8Lh0fj5DcJ+RaKrTYVTGQ,iv:N39gQYshVrsm0sRuMr/rGu/oyMAMHDvZfSRFVhi5oJs=,tag:Q0X4YSNdoY2fDMNN/OObKQ==,type:comment]
#
#ENC[AES256_GCM,data:xEQP700LrwNr8on/c2Bo0fENWsVRwpeQ3CY+v86bzDXG87dnM0sSwOeULteOUTcD2/f6PoIO,iv:iQTdYuT3gklB7LR3d14ZTuJr9yDMl0qbMUwBdksjup0=,tag:21J41JQsN9pQmPeoymFzUA==,type:comment]
apiVersion: ENC[AES256_GCM,data:/dY=,iv:JmVaev1a618JlghP/m5o2Yctl2uGa3FJ/wPQsX5d5tY=,tag:Gd2R6/P5xntgVRJADqFy4A==,type:str]
kind: ENC[AES256_GCM,data:sYceRLAB,iv:rAQba0z5gKZI6yUntVcUemdZ/XW/RRlDSzMePCO51S8=,tag:16JywLFx3wnejk43LBooQA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:bAK2YU9qc4CK2mxkmmYId62xqsM=,iv:VQtFikJWx+mm80Ix0t7biEatY4vzWQ8EJQSQ9lkQvMM=,tag:AKaH6MkRA2bLGFMMEMgqeQ==,type:str]
    namespace: ENC[AES256_GCM,data:/qYxLfRWgIB7/4+p,iv:BPDdxeauVt8jtstT5+a/M1uL1I7jDUN+3JjNopRMPI0=,tag:aAxCtGAQG0jV/jA1JpA4bw==,type:str]
type: ENC[AES256_GCM,data:7nDzYX5n,iv:rndUAmj78VrvIHNkDggPjn3tmbSDZIBFC63VtF7fVMQ=,tag:jemDYE6f2WmH1rKvpvbowA==,type:str]
stringData:
    api-token: ENC[AES256_GCM,data:0HCujccLimuaxQ/vNP3eImrBSFpmVaU8z2KwlbC2BWnouyGa/9i/Yp7n1Z4AQZ36AbMjFuU=,iv:EdUZKEbTFpdS+SMMeC6nIHIFuqBYHOEXx68sHJOyMBg=,tag:oz81vqXXhnwIP0exQbfYHw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmWit1eEtuaGhOUUhXdzBy
            bWNXSHhZTFBTRWFldzh4di9CZE5WUW1ZZ2p3CnlwY2M1MnlGeUdLdFRDYUpZczhI
            RDFpRFpHVUV5dnYreDNWcjBQYWVlM0EKLS0tIEhLZnVpUDlJaG1WVlkyUGI1QmRv
            NnQzM2RKMHU5aHVQektVMTRtMSt3SHMKk3TJNi/tdvNRkaY2HELA7qOfMT8ZXZCZ
            czojw+qWk+bLSpmmoAhTYSvu+Oamp+rYpMgB6j5pxcWX42E1291Z6g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1aea5yspsk9xna076kuuakhpnx7472k8kgl0szq2fluham9mj4uxqdt4kzn
    lastmodified: "2026-06-04T20:07:04Z"
    mac: ENC[AES256_GCM,data:Pc+OSqR4C3OPucnD4AnlIJmrOL5AW8uKBpvTNxwgENkpPmfvE+zWWDKX4KqsgWpsczw80dP3F4VZL/eLOTLBeMHmljCxPqqTXi5guoACc+x+Mxf+62lbXGmcYOUsVCGiHaLKhh7UpO7gA2fsNS0+j3PY0N3emx7YFvSibW0ozLM=,iv:+yCANcStT8hw23AvrbACtKHNKfysLKPVdFNjQDq6FNQ=,tag:zc4dKAiHjUq826lpYzWLGQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
